// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdtdxjzlogxjcnufedpl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkdGR4anpsb2d4amNudWZlZHBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NzAzMzgsImV4cCI6MjA2NzM0NjMzOH0.V_YnvJsi0Iq6lGlPdaC9oTUeTd_WgBatvJ8joJYhmk8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});